### ISSUE TITLE
Error within the usermanagement page

### ISSUE THREAD

**Issue by baukeplugge** [laravel-frontend-presets/white-dashboard#9]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

opening the usermanagement page without an error

# Current Behavior
When I open the usermanagement page I receive an error:
$pageSlug is undefined
Make the variable optional in the blade template. Replace {{ $pageSlug }} with {{ $pageSlug ?? '' }}

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

I have just done a clean install of the template on ubuntu 20.04 with PHP version 8.0.1 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: VMWARE VM
* Operating System: UBUNTU 20.04
* Browser and Version: CHrome Versie 87.0.4280.141 (Officiële build) (64-bits)

## Failure Logs

Please include any relevant log snippets or files here.
![laravel - white template](https://user-images.githubusercontent.com/7989904/105331512-d41f9a00-5bd3-11eb-811c-ceea975d2a92.PNG)

**Comment by teamupdivision** [comment]
Hello @baukeplugge.
Thanks for reporting this issue and for using Creative Tim products.

We've pushed a fix to this problem.
You can either download again the product from the downloads section in the Creative Tim website or check the latest commit we did in this Github repository.

All the best

**Comment by teamupdivision** [comment]
If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
